# Generated by Django 4.2.7 on 2024-04-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IID', models.PositiveBigIntegerField(blank=True)),
                ('DEP_ID', models.IntegerField()),
                ('MED_ID', models.IntegerField()),
                ('ANALOG_ID', models.IntegerField(null=True)),
                ('KOD_SITE', models.IntegerField(null=True)),
                ('QTTY', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('RPRICE_SITE', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('RPRICE', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('SPRICE', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('SALLPRICE', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('VPRICE', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('REG_PRICE', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('date_stock', models.DateTimeField(null=True)),
                ('valid_date', models.DateField(null=True)),
                ('VALID_PERIOD', models.IntegerField(null=True)),
            ],
        ),
    ]
