# Generated by Django 4.2.7 on 2024-04-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_rprice_site_exp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('IID', 'DEP_ID', 'MED_ID')},
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['MED_ID'], name='todo_todo_MED_ID_03c105_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['KOD_SITE'], name='todo_todo_KOD_SIT_0a6a2c_idx'),
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todo_todo',
        ),
    ]
